#!/usr/bin/env bash

open /System/Library/PreferencePanes/Security.prefPane
osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "If you have not enabled FileVault, do so now and restart your machine.\n\n(The Security preference pane has been opened for you.)\n\nOnly click \"OK\" when your drive is encrypted." buttons {"Cancel", "OK"} default button 2'

open /Applications/App\ Store.app
osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "If you have not installed XCode, do so now before clicking \"OK\".\n\n(The App Store has been opened for you.)" buttons {"Cancel", "OK"} default button 2'

echo "Installing Homebrew, a good OS X package manager."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Installing GNU userland tools."
  brew install coreutils gnu-sed findutils

echo "Install git and gist tools."
  brew install git gist

echo "Installing a recent version of curl and wget for HTTP requests."
  brew install curl wget

echo "Installing MySQL, our standard database server."
  brew install mysql
  unset TMPDIR
  mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp
  mysql.server start

echo "Installing Homebrew's PHP with MSSQL, MySQL and internationalization support."
  brew install https://github.com/adamv/homebrew-alt/raw/master/duplicates/php.rb --with-mssql --with-mysql --with-intl
  sed -e's#libexec/apache2/libphp5.so#/usr/local/Cellar/php/5.3.8/libexec/apache2/libphp5.so#;s/#LoadModule php5_module/LoadModule php5_module/' /etc/apache2/httpd.conf > /tmp/httpd.conf
  sudo mv /tmp/httpd.conf /etc/apache2/httpd.conf
  chmod -R ug+w /usr/local/Cellar/php/5.3.8/lib/php
  pear config-set php_ini /usr/local/etc/php.ini

open /System/Library/PreferencePanes/Sharing.prefPane
osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "To prevent issues with Apache, please turn on Web Sharing now.\n\nClick \"OK\" once it has started." buttons {"Cancel", "OK"} default button 2'

echo "Installing bash-completion and putting it into .bash_profile."
  brew install bash-completion

echo '
# Find homebrew prefix if it is available.
brew_prefix=$(brew --prefix)

# Enable bash_completion from brew.
if [ -f $brew_prefix/etc/bash_completion ]; then
  . $brew_prefix/etc/bash_completion
fi

# Put homebrew PHP ahead in $PATH a la http://justinhileman.info/article/reinstalling-php-53-on-mac-os-x/
export PATH=$brew_prefix/sbin:$brew_prefix/bin:$PATH' > ~/.bashrc

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.bashrc
  source ~/.bashrc

echo "Installing Drush, because we <3 Drupal."
  brew install drush

echo "Upping max open files limit."
  [[ -f /etc/launchd.conf ]] || sudo sh -c 'echo "limit maxfiles 16384" > /etc/launchd.conf'

osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "Stop now!" buttons {"Cancel", "OK"} default button 2'

bash < <(curl -s https://raw.github.com/treehouseagency/laptop/master/ruby)

