#!/usr/bin/env bash

function need_sudo {
  osascript -e 'tell app "System Events" to activate'
  osascript -e 'tell app "System Events" to display dialog "Your sudo password is (likely) needed in the Terminal or will be very shortly." buttons {"OK"}'
  osascript -e 'tell app "Terminal" to activate'
}

[[ `diskutil coreStorage list` == 'No CoreStorage logical volume groups found' ]] && {
  osascript -e 'tell app "System Events" to activate'
  osascript -e 'tell app "System Events" to display dialog "Please enable FileVault and restart, then start this process again." buttons {"OK"} default button 1'
  open /System/Library/PreferencePanes/Security.prefPane
  exit 1
}

type -p gcc > /dev/null || {
  osascript -e 'tell app "System Events" to activate'
  osascript -e 'tell app "System Events" to display dialog "Please install XCode now.\n\n(The App Store has been opened for you.)\n\nIf you have installed XCode and still get this dialog, you will need to install the command-line tools by going to Preferences > Downloads in the XCode application." buttons {"Cancel", "OK"} default button 2'
  open /Applications/App\ Store.app
  echo "ERROR: Cannot find gcc. Try starting this process again."
  exit 1
}

echo "Installing Homebrew, a good OS X package manager."
  need_sudo
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Installing GNU userland tools."
  brew install coreutils gnu-sed findutils

echo "Install GitHub-related tools."
  brew install git gist hub

echo "Installing a recent version of curl and wget for HTTP requests."
  brew install curl wget

echo "Installing MySQL, our standard database server."
  curl -fsSL https://raw.github.com/phase2/laptop/master/conf_files/my.cnf > /tmp/my.cnf
  need_sudo
  sudo mv /tmp/my.cnf /etc/my.cnf
  brew install mysql
  unset TMPDIR
  mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp
  mysql.server start

echo "Installing a test phpinfo.php in the new DocumentRoot."
  [[ -d $HOME/htdocs ]] || {
    mkdir $HOME/htdocs
    echo '<?php phpinfo();' > $HOME/htdocs/phpinfo.php
  }

echo "Installing Homebrew's PHP, MSSQL, MySQL and internationalization support."
  brew install https://raw.github.com/josegonzalez/homebrew-php/f09dc1288d839c8d7118a431360d80cd7e9419d2/Formula/php.rb --with-mysql --with-intl
  curl -fsSL https://raw.github.com/phase2/laptop/master/conf_files/httpd.conf | sed -e "s/@@USER@@/$USER/" > /tmp/httpd.conf
  curl -fsSL https://raw.github.com/phase2/laptop/master/conf_files/httpd-extra-config.conf > /tmp/httpd-extra-config.conf
  curl -fsSL https://raw.github.com/phase2/laptop/master/conf_files/httpd-vhosts.conf | sed -e "s/@@USER@@/$USER/" > /tmp/httpd-vhosts.conf
  need_sudo
  sudo mv /tmp/httpd.conf /etc/apache2/httpd.conf
  sudo mv /tmp/httpd-extra-config.conf /etc/apache2/extra/httpd-extra-config.conf
  sudo mv /tmp/httpd-vhosts.conf /etc/apache2/extra/httpd-vhosts.conf
  chmod -R ug+w /usr/local/Cellar/php/5.3.10/lib/php
  pear config-set php_ini /usr/local/etc/php.ini

echo "Installing PHP extensions and a default configuration."
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-apc.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-memcached.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-imagick.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-pcntl.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-xdebug.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-xhprof.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/php53-redis.rb
  brew install https://raw.github.com/josegonzalez/homebrew-php/master/Formula/phpsh.rb
  curl -fsSL https://raw.github.com/phase2/laptop/master/conf_files/php.ini > /tmp/php.ini
  mv /tmp/php.ini /usr/local/etc/php.ini

open /System/Library/PreferencePanes/SharingPref.prefPane
osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "To prevent issues with Apache, please turn on Web Sharing now.\n\nClick \"OK\" once it has started to view the phpinfo() page." buttons {"Cancel", "OK"} default button 2'
open http://localhost/phpinfo.php

echo "Installing bash-completion and putting it into .bash_profile."
  brew install bash-completion

echo '
# Find homebrew prefix if it is available.
brew_prefix=$(brew --prefix)

# Enable bash_completion from brew.
if [ -f $brew_prefix/etc/bash_completion ]; then
  . $brew_prefix/etc/bash_completion
fi

# Put homebrew PHP ahead in $PATH a la http://justinhileman.info/article/reinstalling-php-53-on-mac-os-x/
export PATH=$brew_prefix/sbin:$brew_prefix/bin:$PATH' > $HOME/.bashrc

echo '
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi' > $HOME/.bash_profile

echo "Installing Drush, because we <3 Drupal and the shell."
  pear channel-discover pear.drush.org
  pear install drush/drush

echo "Upping max open files limit."
  [[ -f /etc/launchd.conf ]] || {
    need_sudo
    sudo sh -c 'echo "limit maxfiles 16384" > /etc/launchd.conf'
  }

echo "Installing lots of Drush coolness."
  [[ -d $HOME/.drush ]] || mkdir $HOME/.drush
  cd $HOME/.drush
  drush dl grn
  drush dl phpsh
  drush dl feather
  drush dl drush-vagrant

echo "Downloading VirtualBox for virtualization."
  curl -fsSL http://download.virtualbox.org/virtualbox/4.1.12/VirtualBox-4.1.12-77245-OSX.dmg > $HOME/Downloads/VirtualBox-4.1.12-77245-OSX.dmg
  open $HOME/Downloads/VirtualBox-4.1.12-77245-OSX.dmg

echo "Downloading Vagrant for virtualized dev environments."
  curl -fsSL http://files.vagrantup.com/packages/41445466ee4d376601fd8d0c6a5e3af61d32f131/Vagrant-1.0.2.dmg > $HOME/Downloads/Vagrant-1.0.2.dmg
  open $HOME/Downloads/Vagrant-1.0.2.dmg

osascript -e 'tell app "System Events" to activate'
osascript -e 'tell app "System Events" to display dialog "Please install Vagrant, install VirtualBox and then restart.\n\nWelcome to Phase2!" buttons {"OK"}'
